version: "3.5"

services:

  postgres:
    container_name: "groupomania_postgres"
    image: postgres
    restart: always
    command: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=groupomania
    volumes:
      - postgres:/var/lib/postgresql/data

  adonisjs:
    container_name: "groupomania_backend"
    build:
      context: ./back
    env_file:
     - ./back/.env
    ports:
      - "3333:3333"
    volumes:
      - ./back/:/app
      - /app/node_modules

  vuejs:
    container_name: "groupomania_frontend"
    build:
      context: ./front
    env_file:
     - ./front/.env
    ports:
      - "3000:3000"
    volumes:
      - ./front/:/app
      - /app/node_modules

volumes:
  postgres:
